language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: MiaJFSpKr1HCmhX9L6o5ePstDwwLTfPFKxM/hYdYiyK2R5HAxvn+cEVuh6MfcEO5X6A8SzDRcOhXUCr6iVKjCU9AY1Bt+YmrUtorLtHH3BfTAoedBgvfkIwi4oSkO77j2bos9Xcb0jR3yEgDamoO6Ksy0xjjkIeTSVWC7QafDVG7ViDgZ3BN3EMGhvdi+XwZLtCJaT9TpzkQMwixGRDf9heeKhQ8/jn034UmsclyQdYKF1qBYSlFyQz6j+RcXjN66e4/6zYB5Uul/mkZwIYHfCQOTWPiuGTMVQNGmU/zrNkJdGnSTVlK2/YGa9eQ6gIBSVEDlw7oz57JMowe8obtL6FOvzl0a2pEMZYJlWHAR3HwO6XNcyxLYhgvPp5NQIiy/T5DQmGaGus/I1/mIEsiL5oUbvMtxsOniMmiNxkJGAspuCmD7L0GSV3iln0KMJ7LHhk+ahe7+14Yi+di5J8nyVv60gHWN04WeGzboEIsEW54qOM2oG/pYnKs/FyHoiNT2vSS4bl70+ifp7gVAgG74CE31TmvcfiUmLgUvPvVTEmJXb5a2Cq2h+v0tGx/2C25oavMKEks74/sxVm25doJLChzyN9mk4ACWzLVc5bdTnBUxpYU86YcIj4iMpTyEo5vGORvbi3f/FzI8qUzE6RsCLlEipP7YcLJiMGgT5lW9n8=
