# BananaSpace v1.4_2 - Main Configuration File 
# ----------------------------------------
#     This configuration has a pretty      
#    huge amount of documentation, but     
#   if you still have questions, please    
#        ask on BukkitDev! Thanks.
# Debugging mode
debug: false
# Global settings
global:
    # Spacesuit armortype
    armortype: iron
    # Spacehelmet block id
    blockid: 86
    # Other global settings
    givehelmet: false
    givesuit: false
    usespout: true
# Economy settings
economy:
  # True if economy should be enabled
  enabled: false
  entercommandcost: 20
  exitcommandcost: 20
  entercost: 20
  exitcost: 20
# Space worlds
# This is NOT needed, but it might help.
worlds: []