# BananaSpace v1.4 - Main Configuration File 
# ----------------------------------------
#     This configuration has a pretty      
#    huge amount of documentation, but     
#   if you still have questions, please    
#  ask on our bukkit.org thread! Thanks.   
############################################
# Debugging mode
debug: false
# Global settings
global:
    # Spacesuit armortype
    armortype: iron
    # Spacehelmet block id
    blockid: 86
    # Other global settings
    givehelmet: false
    givesuit: false
    usespout: true
# Economy settings
economy:
  # True if economy should be enabled
  enabled: false
  entercommandcost: 20
  exitcommandcost: 20
  entercost: 20
  exitcost: 20
# Space worlds
worlds:
    world_space:
        # World generation options
        generation:
            generateplanets: true
            generateasteroids: true
            generatesatellites: true
            # From 1-200. These can be turned off with the generateasteroids-setting.
            glowstonechance: 1
            stonechance: 3
            # From 1-1337. This can be turned off with the generatesatellites-setting.
            satellitechance: 1
        # Spacesuit options
        suit:
            required: false
        # Spacehelmet options
        helmet:
            required: false
        # Breathing area options
        breathingarea:
            maxroomheight: 5
        # Miscellaneous options
        weather: false
        nethermode: false
        alwaysnight: true
        neutralmobs: true
        hostilemobs: false