# BananaSpace v2-dev - Main Configuration File 
# ----------------------------------------
#     This configuration has a pretty      
#    huge amount of documentation, but     
#   if you still have questions, please    
#        ask on BukkitDev! Thanks.
# Debugging mode
debug: false
# Global settings
global:
    # Spacesuit armortype
    armortype: iron
    # Spacehelmet block id
    blockid: 86
    # Other global settings
    givehelmet: false
    givesuit: false
    # Spout features (most features require Spoutcraft)
    spout:
      use: true
      # False if clouds should be hidden
      clouds: false
      # True if gravity should be modified
      gravity: true
      # Space texture pack to use (if enabled)
      texturepack: 'https://github.com/downloads/iffa/BananaSpace/spacetexture.zip'
      # True if the space tex. pack should be used
      usetp: true
# Economy settings
economy:
  # True if economy should be enabled
  enabled: false
  # Enter and exit costs (when using BananaSpace's commands)
  entercommandcost: 20
  exitcommandcost: 20
  # Enter and exit costs
  entercost: 20
  exitcost: 20
