authors: [iffa, Canis85, BR, kitskub]
main: me.iffa.bananaspace.BananaSpace
name: BananaSpace
url: http://github.com/BananaCode/BananaSpace
version: '1.2 [Squid]'
softdepend: [Permissions, Spout, Pail]
#load: startup
commands:
  space:
    description: Go to space, back to earth etc.
    usage: |
          /<command> <enter> [spaceworld] - Go to a space world
          /<command> <back> - Go back where you were
          /<command> <help>
    permission: [bananaspace.teleport.enter, bananaspace.teleport.exit]
# Permission nodes
permissions:
  # Permission groups
      # All permissions group
  bananaspace.*:
    description: Access to all BananaSpace commands.
    children:
      bananaspace.teleport.*: true
      # Teleport
  bananaspace.teleport.*:
    description: Access to all teleportation commands.
    children:
      bananaspace.teleport.enter: true
      bananaspace.teleport.exit: true
      bananaspace.teleport.list: true
  # Single permissions
  bananaspace.teleport.enter:
    description: Allows teleporting to space.
    default: op
  bananaspace.teleport.exit:
    description: Allows teleporting out of space.
    default: op
  bananaspace.teleport.list:
    description: Allows requesting list of spaceworlds.
    default: op