# bSpace - plugin.yml
# All developers/contributors are here!
authors: [iffa, kitskub, HACKhalo2, Canis85, BR]
main: me.iffa.bspace.Space
name: bSpace
url: http://github.com/iffa/bSpace
dev-url: http://dev.bukkit.org/server-mods/bSpace
load: startup
#load: startup
version: 'v2-dev'
softdepend: [Spout, Pail, Register]
commands:
  space:
    description: Go to space, back to earth etc.
    usage: |
          /<command> <enter> [spaceworld] - Go to a space world
          /<command> <back> - Go back where you were
          /<command> <list> - Lists all spaceworlds (loaded with config.yml)
          /<command> <help> - Shows help (usage)
          /<command> <about> - About bSpace
# Permission nodes
permissions:
  # Permission groups
      # All permissions group
  bSpace.commands.*:
    description: Access to all bSpace commands.
    children:
      bSpace.teleport.*: true
      # Teleport
  bSpace.teleport.*:
    description: Access to all teleportation commands.
    children:
      bSpace.teleport.enter: true
      bSpace.teleport.exit: true
      bSpace.teleport.list: true
  # Single permissions
  bSpace.teleport.enter:
    description: Allows teleporting to space.
    default: op
  bSpace.teleport.exit:
    description: Allows teleporting out of space.
    default: op
  bSpace.teleport.list:
    description: Allows requesting list of spaceworlds.
    default: op
  bSpace.ignoresuitchecks:
    description: Ignores all suit and helmet checks for the player.
    default: false